image: node:12

variables:
  DOCKER_DRIVER: overlay2
  CYPRESS_CACHE_FOLDER: '$CI_PROJECT_DIR/.cypressCache'

stages:
  - install
  - test
  # - build
  - e2e
  # - docker
  - deploy
  - cleanup

install:
  stage: install
  script: yarn --frozen-lockfile --prefer-offline
  cache:
    key: '$CI_COMMIT_REF_SLUG'
    paths:
      - .cypressCache/
      - node_modules/
  only: [master]

depCheck:
  stage: test
  script: yarn depCheck
  cache:
    policy: pull
    key: '$CI_COMMIT_REF_SLUG'
    paths:
      - node_modules/
  only: [master]

jest:
  stage: test
  script: yarn test:jest
  cache:
    policy: pull
    key: '$CI_COMMIT_REF_SLUG'
    paths:
      - node_modules/
  artifacts:
    reports:
      junit: reports/junitresults.xml
    paths:
      - reports
  only: [master]

lint:
  stage: test
  script: yarn lint
  cache:
    policy: pull
    key: '$CI_COMMIT_REF_SLUG'
    paths:
      - node_modules/
  only: [master]

tsc:
  stage: test
  script: yarn tsc
  cache:
    policy: pull
    key: '$CI_COMMIT_REF_SLUG'
    paths:
      - node_modules/
  only: [master]

build:app:
  stage: test
  variables:
    NODE_ENV: production
  script: yarn build:client
  cache:
    policy: pull
    key: '$CI_COMMIT_REF_SLUG'
    paths:
      - node_modules/
  artifacts:
    paths:
      - dist/client
      - testDist/client
  dependencies: []
  only: [master]

build:server:
  stage: test
  variables:
    NODE_ENV: production
  script: yarn build:server
  cache:
    policy: pull
    key: '$CI_COMMIT_REF_SLUG'
    paths:
      - node_modules/
  artifacts:
    paths:
      - dist/server
      - testDist/server
  dependencies: []
  only: [master]

.cypress_template: &cypress
  image: cypress/browsers:node12.6.0-chrome75
  stage: e2e
  variables:
    BASE_URL: http://localhost:9042
    NODE_ENV: production
    TEST_RUN: 1
  script:
    - yarn cypress cache path
    - node testDist/server/server/index.js & npx wait-on http://localhost:9042
    - yarn e2e:ci --record --parallel||(pkill -9 node && exit 1)
    - pkill -9 node
  cache:
    policy: pull
    key: '$CI_COMMIT_REF_SLUG'
    paths:
      - .cypressCache/
      - node_modules/
  dependencies:
    - build:app
    - build:server
  only: [master]

cypress1:
  <<: *cypress

cypress2:
  <<: *cypress

cypress3:
  <<: *cypress

docker:server:
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  stage: e2e
  script:
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/Dockerfile --destination $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA --destination $CI_REGISTRY_IMAGE
  dependencies:
    - build:server
    - build:app
  only: [master]

deploy:beta:
  stage: deploy
  image: registry.gitlab.com/marudor/deploy-helper
  variables:
    GIT_STRATEGY: none
  script:
    - /helm-upgrade.sh "bahnhofsabfahrten" "bahnhofsabfahrten-beta.yaml" "bahnhofsabfahrten-beta" "$CI_COMMIT_SHA" "marudor"
  environment:
    name: beta
  only: [master]
  dependencies: []

deploy:prod:
  stage: deploy
  image: registry.gitlab.com/marudor/deploy-helper
  variables:
    GIT_STRATEGY: none
  script:
    - /helm-upgrade.sh "bahnhofsabfahrten" "bahnhofsabfahrten.yaml" "bahnhofsabfahrten" "$CI_COMMIT_SHA" "marudor"
  environment:
    name: production
  when: manual
  only:
    - master
  dependencies: []
