# Default values for bahnhofsAbfahrten.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  registryHost: registry.gitlab.com
  repository: docker.pkg.github.com/marudor/bahnhofsabfahrten/standalone
  tag: latest
  pullPolicy: IfNotPresent

nameOverride: ''
fullnameOverride: ''

service:
  type: ClusterIP
  port: 9042

env: []

certificate:
  enabled: false

ingress:
  enabled: false
  annotations:
    {}
  path: /
  hosts:
  tls:

resources:
  {}

nodeSelector: {}

tolerations: []

affinity: {}
