{{- if .Values.ingress.enabled -}}
{{- $fullName := include "bahnhofsAbfahrten.fullname" . -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    app.kubernetes.io/name: {{ include "bahnhofsAbfahrten.name" . }}
    helm.sh/chart: {{ include "bahnhofsAbfahrten.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
{{- with .Values.ingress.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
  tls:
    - hosts:
      {{ if .Values.hostName }}
        - {{ .Values.hostName }}
        {{ if .Values.docs }}
        - docs.{{ .Values.hostName }}
        - www.docs.{{ .Values.hostName }}
        {{ end }}
      {{ else }}
        - {{ .Release.Name }}.marudor.de
        {{ if .Values.docs }}
        - docs.{{ .Release.Name }}.marudor.de
        - www.docs.{{ .Release.Name }}.marudor.de
        {{ end }}
      {{ end }}
      secretName: {{ $fullName }}
  rules:
    {{ if .Values.hostName }}
    - host: {{ .Values.hostName }}
    {{ else }}
    - host: {{ .Release.Name }}.marudor.de
    {{ end }}
      http:
        paths:
          - path: /
            backend:
              serviceName: {{ $fullName }}
              servicePort: http
    {{ if .Values.hostName }}
    - host: www.{{ .Values.hostName }}
    {{ else }}
    - host: www.{{ .Release.Name }}.marudor.de
    {{ end }}
      http:
        paths:
          - path: /
            backend:
              serviceName: {{ $fullName }}
              servicePort: http
    {{ if .Values.docs }}
    {{ if .Values.hostName }}
    - host: docs.{{ .Values.hostName }}
    {{ else }}
    - host: docs.{{ .Release.Name }}.marudor.de
    {{ end }}
      http:
        paths:
          - path: /
            backend:
              serviceName: {{ $fullName }}
              servicePort: docs
    {{ end }}
    {{ if .Values.docs }}
    {{ if .Values.hostName }}
    - host: www.docs.{{ .Values.hostName }}
    {{ else }}
    - host: www.docs.{{ .Release.Name }}.marudor.de
    {{ end }}
      http:
        paths:
          - path: /
            backend:
              serviceName: {{ $fullName }}
              servicePort: docs
    {{ end }}
{{- end }}
