openapi: "3.0.2"
components:
  schemas:
    CommonProductInfo:
      type: object
      properties:
        name:
          type: string
        line:
          type: string
        number:
          type: string
        type:
          type: string
      required:
        - name
    CommonStopInfo:
      type: object
      required:
        - scheduledTime
        - time
      properties:
        scheduledPlatform:
          type: string
        platform:
          type: string
        scheduledTime:
          type: number
        time:
          type: number
        delay:
          type: number
        reihung:
          type: boolean
        messages:
          type: array
          items:
            $ref: "hafas.yaml#/components/schemas/RemL"
        cancelled:
          type: boolean
