openapi: '3.0.2'
components:
  schemas:
    RemL:
      type: object
      properties:
        type:
          type: string
        code:
          type: string
        icoX:
          type: number
        txtN:
          type: string
        txtS:
          type: string
        prio:
          type: number
        sIdx:
          type: number
      required:
        - type
        - code
        - icoX
        - txtN
