openapi: '3.0.2'
info:
  title: Bahnhof Part
  version: '1.0'
servers:
  - url: https://marudor.de/api/bahnhof/v1
tags:
  - name: Bahnhof v1
paths:
  /lageplan/{stationName}:
    get:
      summary: 'Lageplan'
      description: 'Lageplan für einen Bahnhof'
      tags:
        - Bahnhof V1
      parameters:
        - name: stationName
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: 'types/bahnhof.yaml#/components/schemas/LageplanResponse'
