name: betaDeploy
on:
  push:
    branches:
      - main
jobs:
  createDeploy:
    runs-on: ubuntu-latest
    steps:
      - name: 'Create Deployment'
        uses: avakar/create-deployment@v1.0.1
        with:
          ref: ${{ github.sha }}
          task: deploy
          environment: beta
          required_contexts: docker,node
          payload: '{"value_files": ["./config/beta.yml","./config/_common.yml"],"release": "bahnhofs-abfahrten-beta","namespace": "marudor","track": "stable"}'
        env:
          GITHUB_TOKEN: ${{ secrets.DEPLOY_TOKEN }}
