name: cache test

on:
  pull_request:
    branches:
      - master

env:
  CI: 'true'

jobs:
  cacheTest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: use Node.js 14
        uses: actions/setup-node@master
        with:
          node-version: 14
      - name: check
        run: |
          yarn install --immutable --immutable-cache --check-cache
