name: 'Deploy'
on: ['deployment']

jobs:
  deployment:
    if: github.actor != 'github-pages'
    runs-on: 'ubuntu-latest'
    steps:
    - name: 'Checkout'
      uses: 'actions/checkout@v1'
    - name: 'Deploy'
      # Parameters are pulled directly from the GitHub deployment event so the
      # configuration for the job here is very minimal.
      uses: 'deliverybot/helm@master'
      with:
        helm: 'helm3'
        token: '${{ github.token }}'
        secrets: '${{ toJSON(secrets) }}'
        version: '${{ github.sha }}'
        chart: './charts/bahnhofsabfahrten'
        values: |
          image:
            registryHost: docker.pkg.github.com
            repository: docker.pkg.github.com/marudor/bahnhofsabfahrten/standalone
            tag: '${{ github.sha }}'
      env:
        KUBECONFIG_FILE: '${{ secrets.KUBECONFIG }}'
