name: manual deploy

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'where to deploy to? beta or production'
        required: true
        default: beta

jobs:
  createDeploy:
    runs-on: ubuntu-latest
    steps:
      - name: 'Create Deployment'
        uses: avakar/create-deployment@v1.0.1
        with:
          ref: ${{ github.sha }}
          task: deploy
          environment: ${{ github.event.inputs.environment }}
          required_contexts: docker,node,e2e
          payload: '{"value_files": ["./config/${{ github.event.inputs.environment }}.yml","./config/_common.yml"],"release": "bahnhofs-abfahrten-${{ github.event.inputs.environment }}","namespace": "marudor","track": "stable"}'
        env:
          GITHUB_TOKEN: ${{ secrets.DEPLOY_TOKEN }}
