name: PRCleanup
on:
  pull_request:
    types: [closed]

jobs:
  deployment:
    runs-on: 'ubuntu-latest'
    steps:
    - name: 'Deploy'
      uses: 'deliverybot/helm@master'
      with:
        # Task remove means to remove the helm release.
        task: 'remove'
        helm: 'helm3'
        token: '${{ github.token }}'
        release: 'pr-${{ github.event.pull_request.number }}'
        version: '${{ github.sha }}'
        namespace: 'marudor'
        track: 'stable'
        chart: './charts/bahnhofsabfahrten'
      env:
        KUBECONFIG_FILE: '${{ secrets.KUBECONFIG }}'
